
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en suppressHydrationWarning">
      <body
        className={`min-h-screen w-full bg-[#111111] text-white ${inter.className}`}
      >
        <main className="min-h-screen w-full overflow-hidden  ">
          {children}
        </main>
      </body>
    </html>
  );
}
